sonar.projectKey=TEGRASW_Metropolis-perf_SDG_augmentation
sonar.projectName=augmentation
sonar.qualitygate.wait=true
sonar.python.version=3.10

sonar.sources=modules
sonar.tests=tests

sonar.exclusions=\
  **/.venv/**,\
  **/__pycache__/**,\
  **/_logs/**,\
  **/_out/**,\
  **/*.egg-info/**,\
  **/uv.lock

sonar.python.coverage.reportPaths=coverage_report.xml
