# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Unit tests for the registry-driven generation factory."""

from unittest.mock import MagicMock

import pytest

from aug_utils.schema import KNOWN_ADAPTERS
from generation.executors import BaseExecutor
from generation.factory import ADAPTERS, _resolve_seed, create_generator


# ---------------------------------------------------------------------------
# Adapter registry stays in sync with the schema's KNOWN_ADAPTERS
# ---------------------------------------------------------------------------


def test_adapters_match_known_adapters():
    assert set(ADAPTERS) == set(KNOWN_ADAPTERS)


# ---------------------------------------------------------------------------
# _resolve_seed
# ---------------------------------------------------------------------------


class TestResolveSeed:
    def test_none_generates_seed(self):
        seed = _resolve_seed(None, MagicMock())
        assert isinstance(seed, int)
        assert seed > 0

    def test_string_none(self):
        assert isinstance(_resolve_seed("None", MagicMock()), int)

    def test_string_none_lowercase(self):
        assert isinstance(_resolve_seed("none", MagicMock()), int)

    def test_explicit_int(self):
        assert _resolve_seed(42, MagicMock()) == 42

    def test_string_int(self):
        assert _resolve_seed("123", MagicMock()) == 123


# ---------------------------------------------------------------------------
# create_generator — registry dispatch
# ---------------------------------------------------------------------------


def _image_edit_config():
    """A minimal dict config: one image_edit endpoint on the chat adapter."""
    return {
        "augmentation": {
            "model": {"name": "image-edit"},
            "parameters": {
                "seed": 7,
                "num_inference_steps": 30,
                "guidance_scale": 4.0,
            },
        },
        "endpoints": [
            {
                "id": "image_edit",
                "role": "image_edit",
                "url": "http://localhost:8000/v1",
                "model": "test-edit",
                "adapter": "openai.chat.completions",
            }
        ],
    }


class TestCreateGenerator:
    def test_returns_base_executor(self):
        gen = create_generator(_image_edit_config(), MagicMock())
        assert isinstance(gen, BaseExecutor)

    def test_seed_is_set(self):
        gen = create_generator(_image_edit_config(), MagicMock())
        assert gen.seed == 7

    def test_seed_autogenerated_when_none(self):
        config = _image_edit_config()
        config["augmentation"]["parameters"]["seed"] = None
        gen = create_generator(config, MagicMock())
        assert isinstance(gen.seed, int) and gen.seed > 0

    def test_inputs_spec_has_rgb_and_prompt(self):
        gen = create_generator(_image_edit_config(), MagicMock())
        assert "rgb" in gen.inputs_spec
        assert "prompt" in gen.inputs_spec
        assert gen.inputs_spec["rgb"]["required"] is True
        assert gen.inputs_spec["prompt"]["required"] is True

    def test_adapter_is_chat_adapter(self):
        gen = create_generator(_image_edit_config(), MagicMock())
        assert gen.adapter.__class__.__name__ == "OpenAIChatAdapter"

    def test_params_include_modalities_merge(self):
        config = _image_edit_config()
        config["augmentation"]["modalities"] = {"edge": 0.4, "positive_prompt": "x"}
        gen = create_generator(config, MagicMock())
        # Control-modality weights become {control_weight: value} objects so a NIM
        # control input can attach; prompt fields pass through unchanged.
        assert gen.params.get("edge") == {"control_weight": 0.4}
        assert gen.params.get("positive_prompt") == "x"

    def test_missing_augmentation_raises(self):
        with pytest.raises(ValueError, match="augmentation"):
            create_generator({"endpoints": []}, MagicMock())

    def test_unmatched_model_raises(self):
        config = _image_edit_config()
        config["augmentation"]["model"]["name"] = "no-such-model"
        config["endpoints"] = [
            {"id": "vlm", "role": "vlm", "url": "http://x", "model": "m"}
        ]
        with pytest.raises(ValueError, match="no endpoint matched"):
            create_generator(config, MagicMock())


class TestRequestTimeout:
    """pipeline.request_timeout overrides the adapter default only when set."""

    def test_explicit_request_timeout_overrides_default(self):
        config = _image_edit_config()
        config["pipeline"] = {"request_timeout": 5}
        gen = create_generator(config, MagicMock())
        assert gen.adapter.timeout == 5.0

    def test_unset_request_timeout_keeps_adapter_default(self):
        config = _image_edit_config()  # no pipeline section
        gen = create_generator(config, MagicMock())
        assert gen.adapter.timeout == 120.0  # base image-edit default

    def test_endpoint_timeout_wins_over_request_timeout(self):
        config = _image_edit_config()
        config["endpoints"][0]["timeout"] = 42
        config["pipeline"] = {"request_timeout": 5}
        gen = create_generator(config, MagicMock())
        assert gen.adapter.timeout == 42.0

    def test_control_weights_serialized_as_objects(self):
        config = _image_edit_config()
        config["augmentation"]["modalities"] = {
            "edge": 0.4,
            "depth": 0.3,
            "seg": 0.2,
            "vis": 0.1,
            "positive_prompt": "keep",
        }
        gen = create_generator(config, MagicMock())
        assert gen.params["edge"] == {"control_weight": 0.4}
        assert gen.params["depth"] == {"control_weight": 0.3}
        assert gen.params["seg"] == {"control_weight": 0.2}
        assert gen.params["vis"] == {"control_weight": 0.1}
        assert gen.params["positive_prompt"] == "keep"  # prompt unchanged
